encoding: utf-8
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml', 'atom' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
    encoding: utf-8

  -
    type: static
    items_root: /static

base_url:

